/*Generated by SharpKit 5 v4.28.1000*/
if(typeof(JsTypes) == "undefined")
    JsTypes = [];
var WebDE$Color=
{
    fullname:"WebDE.Color",
    baseTypeName:"System.Object",
    staticDefinition:
    {
        cctor:function()
        {
            WebDE.Color.Black = new WebDE.Color.ctor(0,0,0);
            WebDE.Color.White = new WebDE.Color.ctor(255,255,255);
        },
        ToHex:function(val)
        {
            var hexstuff="ABCDEF";
            if(val < 10)
            {
                return val.toString();
            }
            else
            {
                val -= 10;
                return hexstuff.charAt(val).toString();
            }
        },
        FromHex:function(hexValue)
        {
            return new WebDE.Color.ctor(0,0,0);
        }
    },
    assemblyName:"WebDE",
    Kind:"Class",
    definition:
    {
        ctor:function(redVal,greenVal,blueVal)
        {
            this.name = "";
            this.red = 0;
            this.green = 0;
            this.blue = 0;
            System.Object.ctor.call(this);
            this.red = redVal;
            this.green = greenVal;
            this.blue = blueVal;
        },
        GetHex:function()
        {
            var returnString="";
            var redDub=this.red / 16;
            returnString += WebDE.Color.ToHex(WebDE.GameObjects.Helpah.Round$$Double(redDub));
            redDub = this.red % 16;
            returnString += WebDE.Color.ToHex(WebDE.GameObjects.Helpah.Round$$Double(redDub));
            var blueDub=this.blue / 16;
            returnString += WebDE.Color.ToHex(WebDE.GameObjects.Helpah.Round$$Double(blueDub));
            blueDub = this.blue % 16;
            returnString += WebDE.Color.ToHex(WebDE.GameObjects.Helpah.Round$$Double(blueDub));
            var greenDub=this.green / 16;
            returnString += WebDE.Color.ToHex(WebDE.GameObjects.Helpah.Round$$Double(greenDub));
            greenDub = this.green % 16;
            returnString += WebDE.Color.ToHex(WebDE.GameObjects.Helpah.Round$$Double(greenDub));
            return returnString;
        },
        Match:function(colorTomatch)
        {
            if(this.red != colorTomatch.red || this.green != colorTomatch.green || this.blue != colorTomatch.blue)
            {
                return false;
            }
            return true;
        },
        IsOpposite:function(otherColor)
        {
            return true;
        }
    }
};
JsTypes.push(WebDE$Color);
var WebDE$Circle=
{
    fullname:"WebDE.Circle",
    baseTypeName:"System.Object",
    assemblyName:"WebDE",
    Kind:"Class",
    definition:
    {
        ctor:function(left,top,radius)
        {
            this.x = 0;
            this.y = 0;
            this.radius = 0;
            System.Object.ctor.call(this);
            this.x = left;
            this.y = top;
            this.radius = radius;
        },
        Contains:function(point)
        {
            return false;
        }
    }
};
JsTypes.push(WebDE$Circle);
var WebDE$Dimension=
{
    fullname:"WebDE.Dimension",
    baseTypeName:"System.Object",
    assemblyName:"WebDE",
    Kind:"Class",
    definition:
    {
        ctor:function(myWidth,myHeight,myDepth)
        {
            this.width = 0;
            this.height = 0;
            this.depth = 0;
            System.Object.ctor.call(this);
            this.width = myWidth;
            this.height = myHeight;
            this.depth = myDepth;
        },
        ToTuple:function()
        {
            var returnVal=new System.Tuple$2.ctor(System.Double,System.Double,this.width,this.height);
            return returnVal;
        }
    }
};
JsTypes.push(WebDE$Dimension);
var WebDE$Point=
{
    fullname:"WebDE.Point",
    baseTypeName:"System.Object",
    assemblyName:"WebDE",
    Kind:"Class",
    definition:
    {
        ctor:function(theX,theY)
        {
            this.x = 0;
            this.y = 0;
            System.Object.ctor.call(this);
            this.x = theX;
            this.y = theY;
        },
        Distance:function(point2)
        {
            return System.Math.Sqrt(System.Math.Pow(point2.x - this.x,2) + System.Math.Pow(point2.y - this.y,2));
        },
        ToTuple:function()
        {
            var returnVal=new System.Tuple$2.ctor(System.Double,System.Double,this.x,this.y);
            return returnVal;
        }
    }
};
JsTypes.push(WebDE$Point);
var WebDE$Rectangle=
{
    fullname:"WebDE.Rectangle",
    baseTypeName:"System.Object",
    assemblyName:"WebDE",
    Kind:"Class",
    definition:
    {
        ctor:function(left,top,width,height)
        {
            this.x = 0;
            this.y = 0;
            this.width = 0;
            this.height = 0;
            System.Object.ctor.call(this);
            this.x = left;
            this.y = top;
            this.width = width;
            this.height = height;
        },
        Right:function()
        {
            return this.x + this.width;
        },
        Bottom:function()
        {
            return this.y + this.height;
        },
        Contains:function(point)
        {
            if(point.x < this.x || point.y < this.y || point.x > this.width || point.y > this.height)
            {
                return false;
            }
            return true;
        }
    }
};
JsTypes.push(WebDE$Rectangle);
var System$Tuple$1=
{
    fullname:"System.Tuple$1",
    baseTypeName:"System.Object",
    assemblyName:"WebDE",
    Kind:"Class",
    definition:
    {
        ctor:function(T1,item1)
        {
            this.T1 = T1;
            this._item1 = null;
            System.Object.ctor.call(this);
            this._item1 = item1;
        },
        Item1$$:"`0",
        get_Item1:function()
        {
            return this._item1;
        }
    }
};
JsTypes.push(System$Tuple$1);
var System$Tuple$2=
{
    fullname:"System.Tuple$2",
    baseTypeName:"System.Object",
    assemblyName:"WebDE",
    Kind:"Class",
    definition:
    {
        ctor:function(T1,T2,item1,item2)
        {
            this.T1 = T1;
            this.T2 = T2;
            this._item1 = null;
            this._item2 = null;
            System.Object.ctor.call(this);
            this._item1 = item1;
            this._item2 = item2;
        },
        Item1$$:"`0",
        get_Item1:function()
        {
            return this._item1;
        },
        Item2$$:"`1",
        get_Item2:function()
        {
            return this._item2;
        }
    }
};
JsTypes.push(System$Tuple$2);
var WebDE$Vector=
{
    fullname:"WebDE.Vector",
    baseTypeName:"System.Object",
    staticDefinition:
    {
        Distance:function(vector1,vector2)
        {
            return System.Math.Abs$$Double(vector2.y - vector1.y) + System.Math.Abs$$Double(vector2.x - vector1.x);
        }
    },
    assemblyName:"WebDE",
    Kind:"Class",
    definition:
    {
        ctor:function(xMagnitude,yMagnitude)
        {
            this.x = 0;
            this.y = 0;
            System.Object.ctor.call(this);
            this.x = xMagnitude;
            this.y = yMagnitude;
        }
    }
};
JsTypes.push(WebDE$Vector);
