/*Generated by SharpKit 5 v4.28.1000*/
if (typeof($CreateDelegate)=='undefined'){
    if(typeof($iKey)=='undefined') var $iKey = 0;
    if(typeof($pKey)=='undefined') var $pKey = String.fromCharCode(1);
    $CreateDelegate = function(target, func){
        if (target == null || func == null) 
            return func;
        if(func.target==target && func.func==func)
            return func;
        if (target.$delegateCache == null)
            target.$delegateCache = {};
        if (func.$key == null)
            func.$key = $pKey + String(++$iKey);
        var delegate;
        if(target.$delegateCache!=null)
            delegate = target.$delegateCache[func.$key];
        if (delegate == null){
            delegate = function(){
                return func.apply(target, arguments);
            };
            delegate.func = func;
            delegate.target = target;
            delegate.isDelegate = true;
            if(target.$delegateCache!=null)
                target.$delegateCache[func.$key] = delegate;
        }
        return delegate;
    }
}
if(typeof(JsTypes) == "undefined")
    JsTypes = [];
var WebDE$GameObjects$Area=
{
    fullname:"WebDE.GameObjects.Area",
    baseTypeName:"System.Object",
    assemblyName:"WebDE",
    Kind:"Class",
    definition:
    {
        ctor:function(left,top,horizSize,vertSize)
        {
            this.x = 0;
            this.y = 0;
            this.width = 0;
            this.height = 0;
            System.Object.ctor.call(this);
            this.x = left;
            this.y = top;
            this.width = horizSize;
            this.height = vertSize;
        },
        Contains:function(left,top)
        {
            if((left >= this.x && left <= (this.x + this.width)) && (top >= this.y && top <= (this.y + this.height)))
            {
                return true;
            }
            return false;
        }
    }
};
JsTypes.push(WebDE$GameObjects$Area);
var WebDE$GameObjects$GameEntity=
{
    fullname:"WebDE.GameObjects.GameEntity",
    baseTypeName:"System.Object",
    staticDefinition:
    {
        cctor:function()
        {
            WebDE.GameObjects.GameEntity.cachedEntities = new System.Collections.Generic.List$1.ctor(WebDE.GameObjects.GameEntity);
            WebDE.GameObjects.GameEntity.lastid = 0;
        },
        GetById:function(id)
        {
            var $it25=WebDE.GameObjects.GameEntity.cachedEntities.GetEnumerator();
            while($it25.MoveNext())
            {
                var ent=$it25.get_Current();
                if(ent.id == id)
                {
                    return ent;
                }
            }
            return null;
        },
        GetCachedEntities:function()
        {
            return WebDE.GameObjects.GameEntity.cachedEntities;
        },
        isGameEntityLoaded:function()
        {
            return null;
        }
    },
    assemblyName:"WebDE",
    Kind:"Class",
    definition:
    {
        ctor:function(entName)
        {
            this.id = null;
            this.width = 40;
            this.height = 40;
            this.strGameEntityName = "New GameEntity";
            this.sprGameEntitySprite = null;
            this.parentStage = null;
            this.opacity = 1;
            this.visible = true;
            this.customStyles = new System.Collections.Generic.List$1.ctor(System.String);
            this.position = new WebDE.Point.ctor(0,0);
            this.speed = new WebDE.Vector.ctor(0,0);
            this.minSpeed = new WebDE.Vector.ctor(-10,-10);
            this.maxSpeed = new WebDE.Vector.ctor(10,10);
            this.acceleration = 1;
            this.movementAngle = -1;
            this.desiredDirection = 0;
            System.Object.ctor.call(this);
            WebDE.GameObjects.GameEntity.lastid++;
            this.id = "GameEntity_" + WebDE.GameObjects.GameEntity.lastid;
            this.strGameEntityName = entName;
            WebDE.GameObjects.GameEntity.cachedEntities.Add(this);
            var nameSprite=WebDE.Animation.Sprite.GetSpriteByName(this.strGameEntityName);
            this.SetSprite(nameSprite);
        },
        GetId:function()
        {
            return this.id;
        },
        GetName:function()
        {
            return this.strGameEntityName;
        },
        GetPosition:function()
        {
            return this.position;
        },
        SetPosition:function(newX,newY)
        {
            this.position.x = newX;
            this.position.y = newY;
            this.SetNeedsUpdate();
        },
        GetSprite:function()
        {
            return this.sprGameEntitySprite;
        },
        SetSprite:function(newSprite)
        {
            try
            {
                this.sprGameEntitySprite = WebDE.GameObjects.Helpah.Clone(newSprite);
                this.SetNeedsUpdate();
                return true;
            }
            catch(ex)
            {
                WebDE.Debug.log("Exception with SetSprite in GameEntity: " + ex.get_Message());
                return false;
            }
        },
        GetSize:function()
        {
            var returnVal=new System.Tuple$2.ctor(System.Int32,System.Int32,this.width,this.height);
            return returnVal;
        },
        SetSize:function(newWidth,newHeight)
        {
            this.width = newWidth;
            this.height = newHeight;
            this.SetNeedsUpdate();
        },
        GetMovementAngle:function()
        {
            return this.movementAngle;
        },
        SetMovementAngle:function(newAngle)
        {
            this.movementAngle = newAngle;
        },
        GetDirection:function()
        {
            return this.desiredDirection;
        },
        SetDirection:function(newDirection)
        {
            this.desiredDirection = newDirection;
        },
        GetSpeed:function()
        {
            return this.speed;
        },
        SetSpeed:function(newSpeed)
        {
            this.speed = newSpeed;
            this.SetNeedsUpdate();
        },
        AddSpeed:function(newSpeed)
        {
            this.speed.x += newSpeed.x;
            this.speed.y += newSpeed.y;
        },
        GetAcceleration:function()
        {
            return this.acceleration;
        },
        SetAcceleration:function(newAccel)
        {
            this.acceleration = newAccel;
        },
        GetParentStage:function()
        {
            return this.parentStage;
        },
        SetParentStage:function(newStage)
        {
            this.parentStage = newStage;
        },
        Destroy:function()
        {
            WebDE.GameObjects.Stage.CurrentStage.RemoveGameEntity(this);
            WebDE.Rendering.DOM_Renderer.GetRenderer().DestroyGameEntity(this);
            WebDE.GameObjects.Helpah.Destroy(this);
        },
        CalculateSpeed:function()
        {
            if(Is(this,WebDE.GameObjects.GameEntitySpawner))
            {
                return;
            }
            if(this.desiredDirection == -1)
            {
                this.speed.x -= this.acceleration;
            }
            else if(this.desiredDirection == 1)
            {
                this.speed.x += this.acceleration;
            }
            else if(this.desiredDirection == -2)
            {
                this.speed.y -= this.acceleration;
            }
            else if(this.desiredDirection == 2)
            {
                this.speed.y += this.acceleration;
            }
            else if(this.desiredDirection == 0)
            {
                if(this.speed.x > 0)
                {
                    this.speed.x -= this.acceleration;
                }
                else if(this.speed.x < 0)
                {
                    this.speed.x += this.acceleration;
                }
                if(this.speed.y > 0)
                {
                    this.speed.y -= this.acceleration;
                }
                else if(this.speed.y < 0)
                {
                    this.speed.y += this.acceleration;
                }
            }
            if(this.speed.x > this.maxSpeed.x)
            {
                this.speed.x = this.maxSpeed.x;
            }
            if(this.speed.x < this.minSpeed.x)
            {
                this.speed.x = this.minSpeed.x;
            }
            if(this.speed.y > this.maxSpeed.y)
            {
                this.speed.y = this.maxSpeed.y;
            }
            if(this.speed.y < this.minSpeed.y)
            {
                this.speed.y = this.minSpeed.y;
            }
        },
        CalculatePosition:function()
        {
            this.position.x += this.speed.x;
            this.position.y += this.speed.y;
        },
        CheckCollision:function()
        {
        },
        SetNeedsUpdate:function()
        {
            WebDE.Rendering.DOM_Renderer.GetRenderer().SetNeedsUpdate$$GameEntity(this);
        },
        AddCustomStyling:function(styleName)
        {
            if(!this.customStyles.Contains(styleName))
            {
                this.customStyles.Add(styleName);
            }
        },
        GetCustomStyles:function()
        {
            return this.customStyles;
        },
        SetOpcaity:function(newOpacity)
        {
            this.opacity = newOpacity;
            this.SetNeedsUpdate();
        },
        GetOpacity:function()
        {
            return this.opacity;
        },
        Hide:function()
        {
            this.visible = false;
            this.SetNeedsUpdate();
        },
        Show:function()
        {
            this.visible = true;
            this.SetNeedsUpdate();
        },
        Visible:function()
        {
            return this.visible;
        }
    }
};
JsTypes.push(WebDE$GameObjects$GameEntity);
var WebDE$GameObjects$GameEntityBatch=
{
    fullname:"WebDE.GameObjects.GameEntityBatch",
    baseTypeName:"System.Object",
    assemblyName:"WebDE",
    Kind:"Class",
    definition:
    {
        ctor:function(GameEntityType,GameEntityCount,spawnDelay)
        {
            this.GameEntityType = null;
            this.GameEntityCount = 0;
            this.spawnDelay = 0;
            System.Object.ctor.call(this);
            this.GameEntityType = GameEntityType;
            this.GameEntityCount = GameEntityCount;
            this.spawnDelay = spawnDelay;
        }
    }
};
JsTypes.push(WebDE$GameObjects$GameEntityBatch);
var WebDE$GameObjects$GameEntitySpawner=
{
    fullname:"WebDE.GameObjects.GameEntitySpawner",
    baseTypeName:"WebDE.GameObjects.GameEntity",
    staticDefinition:
    {
        cctor:function()
        {
        }
    },
    assemblyName:"WebDE",
    Kind:"Class",
    definition:
    {
        ctor:function(itemName,initialDelay)
        {
            this.spawnBatches = new System.Collections.Generic.List$1.ctor(WebDE.GameObjects.GameEntityBatch);
            this.currentSpawnDelay = 0;
            this.clockId = null;
            WebDE.GameObjects.GameEntity.ctor.call(this,itemName);
            this.currentSpawnDelay = initialDelay;
            WebDE.Timekeeper.Clock.IntervalExecute($CreateDelegate(this,this.Think),1);
        },
        AddGameEntityBatch:function(GameEntityType,GameEntityCount,spawnDelay)
        {
            var newBatch=new WebDE.GameObjects.GameEntityBatch.ctor(GameEntityType,GameEntityCount,spawnDelay);
            this.spawnBatches.Add(newBatch);
        },
        AddGameEntityBatches:function(GameEntityType,GameEntityCount,batchCount,spawnDelay)
        {
            while(batchCount > 0)
            {
                this.AddGameEntityBatch(GameEntityType,GameEntityCount,spawnDelay);
                batchCount--;
            }
        },
        Activate:function()
        {
            this.clockId = WebDE.Timekeeper.Clock.AddCalculation($CreateDelegate(this,this.Think));
        },
        Deactivate:function()
        {
            if(this.clockId != null)
            {
                WebDE.Timekeeper.Clock.RemoveCalculation(this.clockId);
            }
        },
        Think:function()
        {
            if(this.spawnBatches.get_Count() > 0)
            {
                if(this.currentSpawnDelay > 0)
                {
                    this.currentSpawnDelay--;
                    return;
                }
                var batchToSpawn=this.spawnBatches.get_Item$$Int32(0);
                var entitiesToSpawn=this.spawnBatches.get_Item$$Int32(0).GameEntityCount;
                while(entitiesToSpawn > 0)
                {
                    var entSrc=Cast(this.spawnBatches.get_Item$$Int32(0).GameEntityType,WebDE.GameObjects.LivingGameEntity);
                    var newEnt=WebDE.GameObjects.Helpah.Clone(this.spawnBatches.get_Item$$Int32(0).GameEntityType);
                    newEnt.SetPosition(this.GetPosition().x,this.GetPosition().y);
                    newEnt.SetAI(entSrc.GetAI());
                    newEnt.SetParentStage(this.GetParentStage());
                    this.GetParentStage().AddLivingGameEntity(newEnt);
                    entitiesToSpawn--;
                }
                this.currentSpawnDelay = this.spawnBatches.get_Item$$Int32(0).spawnDelay;
                this.spawnBatches.RemoveAt(0);
            }
            else
            {
                this.Deactivate();
            }
        }
    }
};
JsTypes.push(WebDE$GameObjects$GameEntitySpawner);
var WebDE$GameObjects$Helpah=
{
    fullname:"WebDE.GameObjects.Helpah",
    baseTypeName:"System.Object",
    staticDefinition:
    {
        cctor:function()
        {
        },
        Clone:function(o)
        {
            if(o == null)
            {
                return null;
            }
            return $.extend(true,new System.Object.ctor(),o);
        },
        Destroy:function(o)
        {
            o = null;
        },
        Round$$Double:function(number)
        {
            var numString=number.toString();
            if(numString.indexOf(".") > -1)
            {
                numString = numString.substr(0,numString.indexOf("."));
            }
            return System.Int32.Parse$$String(numString);
        },
        Round$$Double$$Int32:function(number,decimalPlaces)
        {
            var numString=number.toString();
            if(numString.indexOf(".") > -1)
            {
                var numString1=numString.substr(0,numString.indexOf("."));
                var numString2=numString.substr(numString.indexOf("."),decimalPlaces + 1);
                numString = numString1 + numString2;
            }
            return parseFloat(numString);
        },
        Parse:function(s)
        {
            var returnVal=0;
            var i=0;
            while(i < s.length)
            {
                if(System.Char.IsDigit$$Char(s.charAt(i)))
                {
                    returnVal = returnVal * 10;
                    returnVal += s.charAt(i);
                }
                i++;
            }
            return returnVal;
        },
        Rand:function(min,max)
        {
            var bit=min + (Math.random() * ((max - min) + 1));
            return Cast(System.Math.Floor$$Double(bit),System.Int32);
        }
    },
    assemblyName:"WebDE",
    Kind:"Class",
    definition:
    {
        ctor:function()
        {
            System.Object.ctor.call(this);
        }
    }
};
JsTypes.push(WebDE$GameObjects$Helpah);
var WebDE$GameObjects$LightSource=
{
    fullname:"WebDE.GameObjects.LightSource",
    baseTypeName:"WebDE.GameObjects.GameEntity",
    staticDefinition:
    {
        cctor:function()
        {
        },
        GetLocalLightSources:function(xPos,yPos)
        {
            var returnLights=new System.Collections.Generic.List$1.ctor(WebDE.GameObjects.LightSource);
            var $it26=WebDE.GameObjects.Stage.CurrentStage.GetLights().GetEnumerator();
            while($it26.MoveNext())
            {
                var light=$it26.get_Current();
                if(light.GetPosition().Distance(new WebDE.Point.ctor(xPos,yPos)) <= light.range)
                {
                    returnLights.Add(light);
                }
            }
            return returnLights;
        }
    },
    assemblyName:"WebDE",
    Kind:"Class",
    definition:
    {
        ctor:function(x,y,lightness,distance)
        {
            this.luminosity = 1;
            this.range = 3;
            this.color = new WebDE.Color.ctor(255,255,255);
            this.needsRenderUpdate = false;
            this.diminishing = false;
            WebDE.GameObjects.GameEntity.ctor.call(this,"");
            this.SetPosition(x,y);
            this.luminosity = lightness;
            this.range = distance;
            if(WebDE.Rendering.View.GetMainView() == null)
            {
                this.CalculateIllumination();
            }
            WebDE.GameObjects.Stage.CurrentStage.AddLight(this);
        },
        GetLuminosity:function()
        {
            return this.luminosity;
        },
        SetLuminosity:function(newVal)
        {
            this.luminosity = newVal;
        },
        GetRange:function()
        {
            return this.range;
        },
        SetRange:function(newRange)
        {
            this.range = newRange;
            this.SetNeedsUpdate();
        },
        GetColor:function()
        {
            return this.color;
        },
        SetColor:function(newColor)
        {
            this.color = newColor;
            this.needsRenderUpdate = true;
        },
        SetDiminishing:function(isDiminishing)
        {
            this.diminishing = isDiminishing;
        },
        GetDiminishing:function()
        {
            return this.diminishing;
        },
        CalculateIllumination:function()
        {
            var localTiles=WebDE.GameObjects.Stage.CurrentStage.GetVisibleTiles(WebDE.Rendering.View.GetMainView());
            var $it27=localTiles.GetEnumerator();
            while($it27.MoveNext())
            {
                var localTile=$it27.get_Current();
                if(localTile.GetPosition().Distance(this.GetPosition()) <= this.range)
                {
                }
            }
        },
        Think:function()
        {
            if(this.GetDiminishing() == true)
            {
                this.SetRange(this.GetRange() - 0.1);
                if(this.GetRange() < 0.1)
                {
                    this.Destroy();
                }
            }
        }
    }
};
JsTypes.push(WebDE$GameObjects$LightSource);
var WebDE$GameObjects$LivingGameEntity=
{
    fullname:"WebDE.GameObjects.LivingGameEntity",
    baseTypeName:"WebDE.GameObjects.GameEntity",
    staticDefinition:
    {
        cctor:function()
        {
        },
        CloneByName:function(lentName)
        {
            var $it28=WebDE.GameObjects.GameEntity.GetCachedEntities().GetEnumerator();
            while($it28.MoveNext())
            {
                var gent=$it28.get_Current();
                if(gent.GetName() == lentName)
                {
                    return gent;
                }
            }
            return null;
        }
    },
    assemblyName:"WebDE",
    Kind:"Class",
    definition:
    {
        ctor:function(entName,health)
        {
            this.health = 0;
            this.ai = null;
            this.weapons = null;
            WebDE.GameObjects.GameEntity.ctor.call(this,entName);
            this.health = health;
            this.ai = new WebDE.AI.ArtificialIntelligence.ctor();
            this.weapons = new System.Collections.Generic.List$1.ctor(WebDE.GameObjects.Weapon);
        },
        GetAI:function()
        {
            return this.ai;
        },
        SetAI:function(newAi)
        {
            this.ai = WebDE.GameObjects.Helpah.Clone(newAi);
            this.ai.SetBody(this);
        },
        Think:function()
        {
            if(this.ai != null)
            {
                this.ai.SetBody(this);
                this.ai.Think();
            }
        },
        Damage:function(Amount)
        {
        },
        Kill:function()
        {
        },
        AddWeapon:function(weaponToAdd)
        {
            weaponToAdd = WebDE.GameObjects.Helpah.Clone(weaponToAdd);
            this.weapons.Add(weaponToAdd);
        },
        GetWeapons:function()
        {
            return this.weapons;
        },
        SetHealth:function(newHealth)
        {
            this.health = newHealth;
        },
        GetHealth:function()
        {
            return this.health;
        }
    }
};
JsTypes.push(WebDE$GameObjects$LivingGameEntity);
var WebDE$GameObjects$Projectile=
{
    fullname:"WebDE.GameObjects.Projectile",
    baseTypeName:"WebDE.GameObjects.LivingGameEntity",
    staticDefinition:
    {
        cctor:function()
        {
        }
    },
    assemblyName:"WebDE",
    Kind:"Class",
    definition:
    {
        ctor:function(projectileName,targetPoint)
        {
            this.damage = 0;
            this.impactEvent = null;
            this.targetPoint = null;
            WebDE.GameObjects.LivingGameEntity.ctor.call(this,projectileName,10);
            this.targetPoint = targetPoint;
            var ai=new WebDE.AI.ArtificialIntelligence.ctor();
        },
        SetPosition:function(newX,newY)
        {
            WebDE.GameObjects.GameEntity.commonPrototype.SetPosition.call(this,newX,newY);
            var newPath=new WebDE.AI.MovementPath.ctor((function()
            {
                var $v1=new System.Collections.Generic.List$1.ctor(WebDE.Point);
                $v1.Add(this.GetPosition());
                $v1.Add(this.targetPoint);
                return $v1;
            }).call(this));
            var newAi=new WebDE.AI.ArtificialIntelligence.ctor();
            newAi.SetMovementPath(newPath);
            this.SetAI(newAi);
        },
        SetDamage:function(newDamage)
        {
            this.damage = newDamage;
        },
        GetDamage:function()
        {
            return this.damage;
        },
        Collision:function()
        {
            if(this.impactEvent != null)
            {
                this.impactEvent();
            }
        }
    }
};
JsTypes.push(WebDE$GameObjects$Projectile);
var WebDE$GameObjects$Resource=
{
    fullname:"WebDE.GameObjects.Resource",
    baseTypeName:"System.Object",
    staticDefinition:
    {
        cctor:function()
        {
            WebDE.GameObjects.Resource.gameResources = new System.Collections.Generic.List$1.ctor(WebDE.GameObjects.Resource);
        },
        GetIdResourceByName:function(resourceName)
        {
            var $it29=WebDE.GameObjects.Resource.gameResources.GetEnumerator();
            while($it29.MoveNext())
            {
                var res=$it29.get_Current();
                if(res.name == resourceName)
                {
                    return res.id;
                }
            }
            return 0;
        },
        ByName:function(resourceName)
        {
            var $it30=WebDE.GameObjects.Resource.gameResources.GetEnumerator();
            while($it30.MoveNext())
            {
                var res=$it30.get_Current();
                if(res.name == resourceName)
                {
                    return res;
                }
            }
            return null;
        }
    },
    assemblyName:"WebDE",
    Kind:"Class",
    definition:
    {
        ctor:function(resourceName)
        {
            this.id = 0;
            this.name = null;
            this.amount = 0;
            System.Object.ctor.call(this);
            this.id = WebDE.GameObjects.Resource.gameResources.get_Count() + 1;
            this.name = resourceName;
            this.amount = 0;
        },
        SetName:function(newName)
        {
        },
        SetAmount:function(newAmount)
        {
        }
    }
};
JsTypes.push(WebDE$GameObjects$Resource);
var WebDE$GameObjects$Stage=
{
    fullname:"WebDE.GameObjects.Stage",
    baseTypeName:"System.Object",
    staticDefinition:
    {
        cctor:function()
        {
            WebDE.GameObjects.Stage.CurrentStage = null;
        }
    },
    assemblyName:"WebDE",
    Kind:"Class",
    definition:
    {
        ctor:function(stageName,stageType)
        {
            this.strStageName = "New Stage";
            this.stageEntities = new System.Collections.Generic.List$1.ctor(WebDE.GameObjects.GameEntity);
            this.livingEntities = new System.Collections.Generic.List$1.ctor(WebDE.GameObjects.LivingGameEntity);
            this.stageTiles = new System.Collections.Generic.List$1.ctor(WebDE.GameObjects.Tile);
            this.stageLights = new System.Collections.Generic.List$1.ctor(WebDE.GameObjects.LightSource);
            this.stageAreas = null;
            this.collisionMap = null;
            this.stageGui = null;
            this.backgroundColor = WebDE.Color.Black;
            this.width = 20;
            this.height = 16;
            this.tileWidth = 40;
            this.tileHeight = 40;
            System.Object.ctor.call(this);
            this.SetName(stageName);
            if(WebDE.GameObjects.Stage.CurrentStage == null)
            {
                WebDE.GameObjects.Stage.CurrentStage = this;
            }
            var viewRect=WebDE.Rendering.View.GetMainView().GetViewArea();
        },
        Load:function()
        {
            var $it31=this.stageEntities.GetEnumerator();
            while($it31.MoveNext())
            {
                var ent=$it31.get_Current();
            }
        },
        getName:function()
        {
            return this.strStageName;
        },
        SetName:function(newName)
        {
            this.strStageName = newName;
        },
        AddGameEntity:function(GameEntityToAdd)
        {
            if(Is(GameEntityToAdd,WebDE.GameObjects.LivingGameEntity) || Is(GameEntityToAdd,WebDE.GameObjects.Tile))
            {
                WebDE.Debug.log("You\'re trying to add a living GameEntity or tile as a regular GameEntity.");
            }
            this.stageEntities.Add(GameEntityToAdd);
            GameEntityToAdd.SetParentStage(this);
        },
        RemoveGameEntity:function(GameEntityToRemove)
        {
            if(Is(GameEntityToRemove,WebDE.GameObjects.LightSource))
            {
                var lightToRemove=Cast(GameEntityToRemove,WebDE.GameObjects.LightSource);
                if(this.stageLights.Contains(lightToRemove))
                {
                    this.stageLights.Remove(lightToRemove);
                }
            }
            else if(Is(GameEntityToRemove,WebDE.GameObjects.Tile))
            {
                var tileToRemove=Cast(GameEntityToRemove,WebDE.GameObjects.Tile);
                if(this.stageTiles.Contains(tileToRemove))
                {
                    this.stageTiles.Remove(tileToRemove);
                }
            }
            else
            {
                if(this.stageEntities.Contains(GameEntityToRemove))
                {
                    this.stageEntities.Remove(GameEntityToRemove);
                }
            }
        },
        AddTile:function(name,walkable,buildable)
        {
            var newTile=new WebDE.GameObjects.Tile.ctor(name,walkable,buildable);
            this.stageTiles.Add(newTile);
            return newTile;
        },
        AppendTile:function(tileToAdd)
        {
            this.stageTiles.Add(tileToAdd);
        },
        AddLivingGameEntity:function(toAdd)
        {
            this.livingEntities.Add(toAdd);
        },
        GetVisibleEntities:function(viewer)
        {
            var resultList=new System.Collections.Generic.List$1.ctor(WebDE.GameObjects.GameEntity);
            var $it32=this.stageEntities.GetEnumerator();
            while($it32.MoveNext())
            {
                var ent=$it32.get_Current();
                resultList.Add(ent);
            }
            var $it33=this.livingEntities.GetEnumerator();
            while($it33.MoveNext())
            {
                var lent=$it33.get_Current();
                resultList.Add(lent);
            }
            return resultList;
        },
        GetVisibleTiles:function(viewer)
        {
            var resultList=new System.Collections.Generic.List$1.ctor(WebDE.GameObjects.GameEntity);
            var $it34=this.stageTiles.GetEnumerator();
            while($it34.MoveNext())
            {
                var tile=$it34.get_Current();
                if(tile.GetLightLevel() != this.GetBackgroundColor() && tile.GetLightLevel() != null)
                {
                    resultList.Add(tile);
                }
            }
            return resultList;
        },
        GetSize:function()
        {
            return new System.Tuple$2.ctor(System.Int32,System.Int32,this.width,this.height);
        },
        SetSize:function(newWidth,newHeight)
        {
            this.width = newWidth;
            this.height = newHeight;
        },
        CreateRandomTiles:function()
        {
            for(var h=0;h < this.height;h++)
            {
                for(var w=0;w < this.width;w++)
                {
                    var rand=Math.round(Math.random());
                    var buildable=false;
                    if(rand == 1)
                    {
                        buildable = true;
                    }
                    var aTile=new WebDE.GameObjects.Tile.ctor("",true,buildable);
                    aTile.SetParentStage(this);
                    aTile.SetPosition(w,h);
                    this.stageTiles.Add(aTile);
                }
            }
        },
        CalculateEntities:function()
        {
            var $it35=this.livingEntities.GetEnumerator();
            while($it35.MoveNext())
            {
                var lent=$it35.get_Current();
                lent.Think();
            }
            var $it36=this.stageEntities.GetEnumerator();
            while($it36.MoveNext())
            {
                var ent=$it36.get_Current();
                try
                {
                }
                catch($$e1)
                {
                }
            }
            var $it37=this.livingEntities.GetEnumerator();
            while($it37.MoveNext())
            {
                var ent=$it37.get_Current();
                if(Is(ent,WebDE.GameObjects.Projectile))
                {
                    if(!this.GetBounds().Contains(ent.GetPosition()))
                    {
                        WebDE.Debug.log(ent.GetPosition().x + "," + ent.GetPosition().y + " isn\'t in " + this.GetBounds().x + "," + this.GetBounds().width + "," + this.GetBounds().y + "," + this.GetBounds().height);
                        ent.Destroy();
                    }
                }
            }
        },
        CalculateGameEntityPhysics:function()
        {
            var $it38=this.stageEntities.GetEnumerator();
            while($it38.MoveNext())
            {
                var ent=$it38.get_Current();
                ent.CalculateSpeed();
                ent.CalculatePosition();
            }
            var $it39=this.livingEntities.GetEnumerator();
            while($it39.MoveNext())
            {
                var lent=$it39.get_Current();
                lent.CalculateSpeed();
                lent.CalculatePosition();
            }
        },
        CalculateLights:function()
        {
            for(var i=0;i < this.GetLights().get_Count();i++)
            {
                var light=this.GetLights().get_Item$$Int32(i);
                if(light != null)
                {
                    light.Think();
                }
            }
        },
        GetTileSize:function()
        {
            return new System.Tuple$2.ctor(System.Int32,System.Int32,this.tileWidth,this.tileHeight);
        },
        SetTileSize:function(newWidth,newHeight)
        {
            this.tileWidth = newWidth;
            this.tileHeight = newHeight;
        },
        GetLights:function()
        {
            return this.stageLights;
        },
        AddLight:function(newLight)
        {
            if(!this.stageLights.Contains(newLight))
            {
                this.stageLights.Add(newLight);
            }
        },
        Subdivide:function()
        {
            this.stageAreas = new System.Collections.Generic.List$1.ctor(WebDE.GameObjects.Area);
            return this.stageAreas;
        },
        IsSubdivided:function()
        {
            if(this.stageAreas == null)
            {
                return false;
            }
            else
            {
                return true;
            }
        },
        GetCollisionMap:function()
        {
            if(this.collisionMap == null)
            {
                this.RenderCollisionMap();
            }
            return this.collisionMap;
        },
        RenderCollisionMap:function()
        {
            this.collisionMap = WebDE.GUI.GuiLayer.AsCollisionMap(this);
        },
        ShowCollisionMap:function()
        {
            if(this.collisionMap == null)
            {
                this.RenderCollisionMap();
            }
            this.collisionMap.Activate();
            this.collisionMap.Show();
        },
        HideCollisionMap:function()
        {
            this.collisionMap.Deactivate();
            this.collisionMap.Hide();
        },
        GetBounds:function()
        {
            return new WebDE.Rectangle.ctor(0,0,this.width,this.height);
        },
        GetTileAt:function(xPos,yPos)
        {
            var $it40=this.stageTiles.GetEnumerator();
            while($it40.MoveNext())
            {
                var tile=$it40.get_Current();
                if(tile.GetPosition().x == xPos && tile.GetPosition().y == yPos)
                {
                    return tile;
                }
            }
            return null;
        },
        GetEntitiesNear:function(p,distance)
        {
            var returnVals=new System.Collections.Generic.List$1.ctor(WebDE.GameObjects.GameEntity);
            var $it41=this.stageEntities.GetEnumerator();
            while($it41.MoveNext())
            {
                var gent=$it41.get_Current();
                if(gent.GetPosition().Distance(p) <= distance)
                {
                    returnVals.Add(gent);
                }
            }
            var $it42=this.livingEntities.GetEnumerator();
            while($it42.MoveNext())
            {
                var gent=$it42.get_Current();
                if(gent.GetPosition().Distance(p) <= distance)
                {
                    returnVals.Add(gent);
                }
            }
            return returnVals;
        },
        GetLightsNear:function(p,distance)
        {
            var returnVals=new System.Collections.Generic.List$1.ctor(WebDE.GameObjects.LightSource);
            var $it43=this.stageLights.GetEnumerator();
            while($it43.MoveNext())
            {
                var light=$it43.get_Current();
                if(light.GetPosition().Distance(p) <= distance)
                {
                    returnVals.Add(light);
                }
            }
            return returnVals;
        },
        GetBackgroundColor:function()
        {
            return this.backgroundColor;
        },
        SetBackgroundColor:function(newColor)
        {
            this.backgroundColor = newColor;
        }
    }
};
JsTypes.push(WebDE$GameObjects$Stage);
var WebDE$GameObjects$Tile=
{
    fullname:"WebDE.GameObjects.Tile",
    baseTypeName:"WebDE.GameObjects.GameEntity",
    staticDefinition:
    {
        cctor:function()
        {
            WebDE.GameObjects.Tile.loadedTiles = new System.Collections.Generic.List$1.ctor(WebDE.GameObjects.Tile);
        },
        GetByName:function(tileName)
        {
            var newTile=null;
            var $it44=WebDE.GameObjects.Tile.loadedTiles.GetEnumerator();
            while($it44.MoveNext())
            {
                var tile=$it44.get_Current();
                if(tile.GetName() == tileName)
                {
                    newTile = new WebDE.GameObjects.Tile.ctor(tileName,tile.GetWalkable(),tile.GetBuildable());
                    return newTile;
                }
            }
            if(newTile == null)
            {
                newTile = new WebDE.GameObjects.Tile.ctor(tileName,true,true);
            }
            return newTile;
        },
        oldGetByName:function(tileName)
        {
            var $it45=WebDE.GameObjects.Tile.loadedTiles.GetEnumerator();
            while($it45.MoveNext())
            {
                var tile=$it45.get_Current();
                if(tile.GetName() == tileName)
                {
                    return WebDE.GameObjects.Helpah.Clone(tile);
                }
            }
            return null;
        }
    },
    assemblyName:"WebDE",
    Kind:"Class",
    definition:
    {
        ctor:function(tileName,canWalk,canBuild)
        {
            this.lightLevel = null;
            this.isWalkable = false;
            this.isBuildable = false;
            WebDE.GameObjects.GameEntity.ctor.call(this,tileName);
            this.isWalkable = canWalk;
            this.isBuildable = canBuild;
            WebDE.GameObjects.Tile.loadedTiles.Add(this);
        },
        GetLightLevel:function()
        {
            return this.lightLevel;
        },
        SetLightLevel:function(newLevel)
        {
            this.lightLevel = new WebDE.Color.ctor(newLevel.red,newLevel.green,newLevel.blue);
        },
        CalculateLightLevel:function()
        {
            this.SetLightLevel(WebDE.Color.Black);
            var localLights=WebDE.GameObjects.LightSource.GetLocalLightSources(this.GetPosition().x,this.GetPosition().y);
            if(localLights.get_Count() == 0)
            {
                return this.lightLevel;
            }
            var reds=new System.Collections.Generic.List$1.ctor(System.Int32);
            var blues=new System.Collections.Generic.List$1.ctor(System.Int32);
            var greens=new System.Collections.Generic.List$1.ctor(System.Int32);
            var $it46=localLights.GetEnumerator();
            while($it46.MoveNext())
            {
                var currentLight=$it46.get_Current();
                var dist=this.GetPosition().Distance(currentLight.GetPosition());
                var diminishAmount=dist * 0.1;
                var newRed=(currentLight.GetColor().red - WebDE.GameObjects.Helpah.Round$$Double(currentLight.GetColor().red * diminishAmount));
                var newGreen=(currentLight.GetColor().green - WebDE.GameObjects.Helpah.Round$$Double(currentLight.GetColor().green * diminishAmount));
                var newBlue=(currentLight.GetColor().blue - WebDE.GameObjects.Helpah.Round$$Double(currentLight.GetColor().blue * diminishAmount));
                reds.Add(newRed);
                greens.Add(newGreen);
                blues.Add(newBlue);
            }
            var avgRed=0,avgBlue=0,avgGreen=0;
            var $it47=reds.GetEnumerator();
            while($it47.MoveNext())
            {
                var curRed=$it47.get_Current();
                avgRed += curRed;
            }
            var $it48=blues.GetEnumerator();
            while($it48.MoveNext())
            {
                var curBlue=$it48.get_Current();
                avgBlue += curBlue;
            }
            var $it49=greens.GetEnumerator();
            while($it49.MoveNext())
            {
                var curGreen=$it49.get_Current();
                avgGreen += curGreen;
            }
            this.lightLevel.red = avgRed = avgRed / reds.get_Count();
            this.lightLevel.blue = avgBlue = avgBlue / blues.get_Count();
            this.lightLevel.green = avgGreen = avgGreen / greens.get_Count();
            return this.lightLevel;
        },
        old_CalculateLightLevel:function()
        {
            this.SetLightLevel(WebDE.Color.Black);
            var localLights=WebDE.GameObjects.LightSource.GetLocalLightSources(this.GetPosition().x,this.GetPosition().y);
            var $it50=localLights.GetEnumerator();
            while($it50.MoveNext())
            {
                var currentLight=$it50.get_Current();
                var dist=this.GetPosition().Distance(currentLight.GetPosition());
                var diminishAmount=dist * 0.1;
                var calculatedColor=new WebDE.Color.ctor(currentLight.GetColor().red - WebDE.GameObjects.Helpah.Round$$Double(currentLight.GetColor().red * diminishAmount),currentLight.GetColor().green - WebDE.GameObjects.Helpah.Round$$Double(currentLight.GetColor().green * diminishAmount),currentLight.GetColor().blue - WebDE.GameObjects.Helpah.Round$$Double(currentLight.GetColor().blue * diminishAmount));
                if(calculatedColor.red > this.lightLevel.red)
                {
                    this.lightLevel.red = calculatedColor.red;
                }
                if(calculatedColor.green > this.lightLevel.green)
                {
                    this.lightLevel.green = calculatedColor.green;
                }
                if(calculatedColor.blue > this.lightLevel.blue)
                {
                    this.lightLevel.blue = calculatedColor.blue;
                }
            }
            return this.lightLevel;
        },
        GetBuildable:function()
        {
            return this.isBuildable;
        },
        SetBuildable:function(buildable)
        {
            this.isBuildable = buildable;
        },
        GetWalkable:function()
        {
            return this.isWalkable;
        },
        SetWalkable:function(walkable)
        {
            this.isWalkable = walkable;
        }
    }
};
JsTypes.push(WebDE$GameObjects$Tile);
var WebDE$GameObjects$Weapon=
{
    fullname:"WebDE.GameObjects.Weapon",
    baseTypeName:"System.Object",
    assemblyName:"WebDE",
    Kind:"Class",
    definition:
    {
        ctor:function(owner,damage,firingInterval,projectileSpeed,turningRadius,turnSpeed)
        {
            this.maxAmmo = 100;
            this.currentAmmo = 100;
            this.range = 0;
            this.turningRadius = 0;
            this.turningSpeed = 0;
            this.projectileSpeed = 0;
            this.damage = 0;
            this.projectileType = null;
            this.firingDelay = 0;
            this.lastFiredTime = 0;
            this.owner = null;
            this.target = null;
            this.fireWhileMoving = false;
            System.Object.ctor.call(this);
            this.owner = owner;
            this.damage = damage;
            this.firingDelay = firingInterval * 1000;
            this.projectileSpeed = projectileSpeed;
            this.turningRadius = turningRadius;
            this.turningSpeed = turnSpeed;
            this.lastFiredTime = System.DateTime.get_Now().get_Millisecond() - WebDE.GameObjects.Helpah.Round$$Double(this.firingDelay);
        },
        SimpleFire:function()
        {
        },
        Fire:function()
        {
            if(this.owner.GetParentStage() == null)
            {
                return;
            }
            if(System.DateTime.get_Now().get_Millisecond() > this.lastFiredTime + this.firingDelay)
            {
                WebDE.Debug.log("Ima firin mah lazer");
                var deltaX=Cast(System.Math.Round$$Double(this.owner.GetPosition().x - this.GetTarget().GetPosition().x),System.Int32);
                var deltaY=Cast(System.Math.Round$$Double(this.owner.GetPosition().y - this.GetTarget().GetPosition().y),System.Int32);
                var myBullet=new WebDE.GameObjects.Projectile.ctor("Bullet",this.GetTarget().GetPosition());
                myBullet.SetParentStage(this.owner.GetParentStage());
                myBullet.SetDamage(10);
                myBullet.SetPosition(this.owner.GetPosition().x,this.owner.GetPosition().y);
                myBullet.SetSpeed(new WebDE.Vector.ctor(deltaX,deltaY));
                WebDE.GameObjects.Stage.CurrentStage.AddLivingGameEntity(myBullet);
                this.SetCurrentAmmo(this.GetCurrentAmmo() - 1);
            }
        },
        SetCurrentAmmo:function(newAmmo)
        {
            this.currentAmmo = newAmmo;
        },
        GetCurrentAmmo:function()
        {
            return this.currentAmmo;
        },
        SetMaxAmmo:function(newAmmo)
        {
            this.maxAmmo = newAmmo;
        },
        GetMaxAmmo:function()
        {
            return this.maxAmmo;
        },
        SetRange:function(newRange)
        {
            this.range = newRange;
        },
        GetRange:function()
        {
            return this.range;
        },
        SetProjectileSpeed:function(newSpeed)
        {
            this.projectileSpeed = newSpeed;
        },
        GetProjectileSpeed:function()
        {
            return this.projectileSpeed;
        },
        SetTurningSpeed:function(newSpeed)
        {
            this.turningSpeed = newSpeed;
        },
        GetTurningSpeed:function()
        {
            return this.turningSpeed;
        },
        SetProjectile:function(newProjectile)
        {
            this.projectileType = newProjectile;
        },
        GetProjectile:function()
        {
            return this.projectileType;
        },
        SetFiringDelay:function(newDelay)
        {
            this.firingDelay = newDelay * 1000;
        },
        GetFiringDealy:function()
        {
            return this.firingDelay / 1000;
        },
        SetTarget:function(newTarget)
        {
            this.target = newTarget;
        },
        GetTarget:function()
        {
            return this.target;
        }
    }
};
JsTypes.push(WebDE$GameObjects$Weapon);
