/*Generated by SharpKit 5 v4.27.4000*/
function $CombineDelegates(del1,del2)
{
    if(del1 == null)
        return del2;
    if(del2 == null)
        return del1;
    var del=$CreateMulticastDelegateFunction();
    del.delegates = [];
    if(del1.isMulticastDelegate)
    {
        for(var i=0;i < del1.delegates.length;i++)
            del.delegates.push(del1.delegates[i]);
    }
    else
    {
        del.delegates.push(del1);
    }
    if(del2.isMulticastDelegate)
    {
        for(var i=0;i < del2.delegates.length;i++)
            del.delegates.push(del2.delegates[i]);
    }
    else
    {
        del.delegates.push(del2);
    }
    return del;
};
function $CreateMulticastDelegateFunction()
{
    var del=function()
    {
        var del2=arguments.callee;
        var x=undefined;
        for(var i=0;i < del2.delegates.length;i++)
        {
            var del3=del2.delegates[i];
            x = del3.apply(null,arguments);
        }
        return x;
    };
    del.isMulticastDelegate = true;
    return del;
};
if(typeof(JsTypes) == "undefined")
    JsTypes = [];
var WebDE$Net$test=
{
    fullname:"WebDE.Net.test",
    baseTypeName:"System.Object",
    staticDefinition:
    {
        cctor:function()
        {
            WebDE.Net.test.client = null;
        },
        StartTest:function()
        {
            WebDE.Net.test.client = new WebDE.Net.NetworkClient.ctor("localhost",81);
            WebDE.Net.test.client.Connect();
            WebDE.Net.test.client.OnConnect = $CombineDelegates(WebDE.Net.test.client.OnConnect,WebDE.Net.test.client_OnConnect);
            WebDE.Net.test.client.OnDisconnect = $CombineDelegates(WebDE.Net.test.client.OnDisconnect,WebDE.Net.test.client_OnDisconnect);
            WebDE.Net.test.client.OnReceive = $CombineDelegates(WebDE.Net.test.client.OnReceive,WebDE.Net.test.client_OnReceive);
        },
        client_OnReceive:function(message)
        {
            document.getElementById("output").innerText = JSON.stringify(message);
        },
        client_OnConnect:function()
        {
            var req=
            {
                get_action:function()
                {
                    return 0;
                },
                get_type:function()
                {
                    return 0;
                },
                get_mapid:function()
                {
                    return 1;
                }
            };
            WebDE.Net.test.client.Send(req);
        },
        client_OnDisconnect:function()
        {
            document.getElementById("output").innerText = "DISCONNECTED!";
        }
    },
    assemblyName:"WebDE.Net",
    Kind:"Class",
    definition:
    {
        ctor:function()
        {
            System.Object.ctor.call(this);
        }
    }
};
JsTypes.push(WebDE$Net$test);
