/* Generated by SharpKit 5 v5.4.4 */
if (typeof($CreateAnonymousObject)=='undefined') 
{
    var $CreateAnonymousObject = function(json)
    {
        var obj = new System.Object.ctor();
        obj.d = json;
        for(var p in json){
            obj['get_'+p] = new Function('return this.d.'+p+';');
        }
        return obj;
    }
}


if (typeof(JsTypes) == "undefined")
    var JsTypes = [];
var WebDE$Net$test = {
    fullname: "WebDE.Net.test",
    baseTypeName: "System.Object",
    staticDefinition: {
        cctor: function (){
            WebDE.Net.test.client = null;
        },
        StartTest: function (){
            WebDE.Net.test.client = new WebDE.Net.NetworkClient.ctor("localhost", 81);
            WebDE.Net.test.client.Connect();
            WebDE.Net.test.client.add_OnConnect(WebDE.Net.test.client_OnConnect);
            WebDE.Net.test.client.add_OnDisconnect(WebDE.Net.test.client_OnDisconnect);
            WebDE.Net.test.client.add_OnReceive(WebDE.Net.test.client_OnReceive);
        },
        client_OnReceive: function (message){
            document.getElementById("output").innerText = JSON.stringify(message);
        },
        client_OnConnect: function (){
            var req = $CreateAnonymousObject({
                action: 0,
                type: 0,
                mapid: 0
            });
            WebDE.Net.test.client.Send(req);
        },
        client_OnDisconnect: function (){
            document.getElementById("output").innerText = "DISCONNECTED!";
        }
    },
    assemblyName: "WebDE.Net",
    Kind: "Class",
    definition: {
        ctor: function (){
            System.Object.ctor.call(this);
        }
    }
};
JsTypes.push(WebDE$Net$test);

