/*Generated by SharpKit 5 v4.28.1000*/
if(typeof(JsTypes) == "undefined")
    JsTypes = [];
var MapEditor$Login=
{
    fullname:"MapEditor.Login",
    baseTypeName:"System.Object",
    staticDefinition:
    {
        cctor:function()
        {
        },
        TryLogin:function()
        {
            var password=$("#password").text();
            var username=$("#username").text();
            MapEditor.MapEditor.get_Server().GetApikey(username,password,MapEditor.Login.LoginCallback);
        },
        LoginCallback:function(result)
        {
            alert(result["apikey"].toString());
        }
    },
    assemblyName:"MapEditor",
    Kind:"Class",
    definition:
    {
        ctor:function()
        {
            System.Object.ctor.call(this);
        }
    }
};
JsTypes.push(MapEditor$Login);
var MapEditor$Views=
{
    fullname:"MapEditor.Views",
    baseTypeName:"System.Object",
    staticDefinition:
    {
        cctor:function()
        {
        },
        Login$$:"System.String",
        get_Login:function()
        {
            return "Login";
        },
        Editor$$:"System.String",
        get_Editor:function()
        {
            return "Editor";
        },
        LoadView:function(view)
        {
            $("#" + view).css("display","block");
        }
    },
    assemblyName:"MapEditor",
    Kind:"Class",
    definition:
    {
        ctor:function()
        {
            System.Object.ctor.call(this);
        }
    }
};
JsTypes.push(MapEditor$Views);
var MapEditor$MapEditor=
{
    fullname:"MapEditor.MapEditor",
    baseTypeName:"System.Object",
    staticDefinition:
    {
        cctor:function()
        {
        },
        Server$$:"WebDE.Net.GameClient",
        get_Server:function(){return this._Server;},
        set_Server:function(value){this._Server = value;},
        Initialize:function()
        {
            MapEditor.MapEditor.set_Server(new WebDE.Net.GameClient.ctor("localhost",81));
            MapEditor.Views.LoadView(MapEditor.Views.get_Login());
        }
    },
    assemblyName:"MapEditor",
    Kind:"Class",
    definition:
    {
        ctor:function()
        {
            System.Object.ctor.call(this);
        }
    }
};
JsTypes.push(MapEditor$MapEditor);
