/*Generated by SharpKit 5 v4.28.1000*/
if(typeof(JsTypes) == "undefined")
    JsTypes = [];
var MapEditor$MapEditor=
{
    fullname:"MapEditor.MapEditor",
    baseTypeName:"System.Object",
    staticDefinition:
    {
        cctor:function()
        {
        },
        DefaultClient_Load:function()
        {
            $(document.body).append("Ready<br/>");
        }
    },
    assemblyName:"MapEditor",
    Kind:"Class",
    definition:
    {
        ctor:function()
        {
            System.Object.ctor.call(this);
        }
    }
};
JsTypes.push(MapEditor$MapEditor);
