/*Generated by SharpKit 5 v4.28.9000*/
if(typeof(JsTypes) == "undefined")
    var JsTypes=[];
var MapEditor$Login=
{
    fullname:"MapEditor.Login",
    baseTypeName:"System.Object",
    staticDefinition:
    {
        cctor:function()
        {
        },
        TryLogin:function()
        {
            var password=$("#password").text();
            var username=$("#username").text();
            MapEditor.MapEditor.get_Server().GetApikey(username,password,MapEditor.Login.ApiKeyCallback);
            MapEditor.MapEditor.get_Server().GetGroups(MapEditor.Login.GroupsCallback);
        },
        ApiKeyCallback:function(result)
        {
            alert(result["apikey"].toString());
        },
        GroupsCallback:function(result)
        {
            alert(result.toString());
        }
    },
    assemblyName:"MapEditor",
    Kind:"Class",
    definition:
    {
        ctor:function()
        {
            System.Object.ctor.call(this);
        }
    }
};
JsTypes.push(MapEditor$Login);
var MapEditor$Views=
{
    fullname:"MapEditor.Views",
    baseTypeName:"System.Object",
    staticDefinition:
    {
        cctor:function()
        {
        },
        Login$$:"System.String",
        get_Login:function()
        {
            return "Login";
        },
        Editor$$:"System.String",
        get_Editor:function()
        {
            return "Editor";
        },
        LoadView:function(view)
        {
            $("#" + view).css("display","block");
        }
    },
    assemblyName:"MapEditor",
    Kind:"Class",
    definition:
    {
        ctor:function()
        {
            System.Object.ctor.call(this);
        }
    }
};
JsTypes.push(MapEditor$Views);
var MapEditor$MapEditor=
{
    fullname:"MapEditor.MapEditor",
    baseTypeName:"System.Object",
    staticDefinition:
    {
        cctor:function()
        {
        },
        Server$$:"WebDE.Net.GameClient",
        get_Server:function(){return this._Server;},
        set_Server:function(value){this._Server = value;},
        Initialize:function()
        {
            var box=new UITK.ImageBox.ctor(100,200,"");
            UITK.Surface.AddComponent(box,300,400);
            UITK.Surface.Validate();
        }
    },
    assemblyName:"MapEditor",
    Kind:"Class",
    definition:
    {
        ctor:function()
        {
            System.Object.ctor.call(this);
        }
    }
};
JsTypes.push(MapEditor$MapEditor);
