/*Generated by SharpKit 5 v4.28.9000*/
if(typeof(JsTypes) == "undefined")
    var JsTypes=[];
var UITK$ImageBox=
{
    fullname:"UITK.ImageBox",
    baseTypeName:"UITK.UITKComponentBase",
    assemblyName:"UITK",
    Kind:"Class",
    definition:
    {
        ctor:function(height,width,source)
        {
            this.src = System.String.Empty;
            UITK.UITKComponentBase.ctor.call(this);
            this.set_Height(height);
            this.set_Width(width);
            this.src = source;
        },
        Source$$:"System.String",
        get_Source:function()
        {
            return this.src;
        },
        set_Source:function(value)
        {
            this.src = value;
        },
        Validate:function()
        {
            this.recreateHTML();
            UITK.Surface.Redraw(this);
        },
        recreateHTML:function()
        {
            var markup="<img ";
            markup += "src=\'" + this.get_Source() + "\' ";
            markup += "id=\'" + this.get_Id() + "\' ";
            markup += "width=\'" + this.get_Width() + "\' ";
            markup += "height=\'" + this.get_Height() + "\' ";
            markup += "/>";
            this.get_Markup().SetMarkup(markup);
            this.get_Styles().SetRule$$String$$String("left",this.get_Position().get_X().toString());
            this.get_Styles().SetRule$$String$$String("right",this.get_Position().get_Y().toString());
        }
    }
};
JsTypes.push(UITK$ImageBox);
var UITK$UITKComponent={fullname:"UITK.UITKComponent",baseTypeName:"System.Object",assemblyName:"UITK",Kind:"Interface"};
JsTypes.push(UITK$UITKComponent);
var UITK$UITKComponentBase=
{
    fullname:"UITK.UITKComponentBase",
    baseTypeName:"System.Object",
    assemblyName:"UITK",
    interfaceNames:["UITK.UITKComponent"],
    Kind:"Class",
    definition:
    {
        ctor:function()
        {
            this.internalHeight = 0;
            this.internalWidth = 0;
            this.internalPosition = new UITK.UITKPosition.ctor(0,0);
            this.internalStyles = new UITK.UITKStyles.ctor();
            this.internalMarkup = new UITK.UITKMarkup.ctor("");
            this.internalId = System.String.Empty;
            System.Object.ctor.call(this);
        },
        Height$$:"System.Int32",
        get_Height:function()
        {
            return this.internalHeight;
        },
        set_Height:function(value)
        {
            this.internalHeight = value;
        },
        Width$$:"System.Int32",
        get_Width:function()
        {
            return this.internalWidth;
        },
        set_Width:function(value)
        {
            this.internalWidth = value;
        },
        Position$$:"UITK.UITKPosition",
        get_Position:function()
        {
            return this.internalPosition;
        },
        set_Position:function(value)
        {
            this.internalPosition = value;
        },
        Styles$$:"UITK.UITKStyles",
        get_Styles:function()
        {
            return this.internalStyles;
        },
        set_Styles:function(value)
        {
            this.internalStyles = value;
        },
        Markup$$:"UITK.UITKMarkup",
        get_Markup:function()
        {
            return this.internalMarkup;
        },
        set_Markup:function(value)
        {
            this.internalMarkup = value;
        },
        Id$$:"System.String",
        get_Id:function()
        {
            if(this.internalId != System.String.Empty)
                return this.internalId;
            this.internalId = UITK.Surface.GenerateID();
            return this.internalId;
        }
    }
};
JsTypes.push(UITK$UITKComponentBase);
var UITK$UITKMarkup=
{
    fullname:"UITK.UITKMarkup",
    baseTypeName:"System.Object",
    assemblyName:"UITK",
    Kind:"Class",
    definition:
    {
        ctor:function(html)
        {
            this.markup = System.String.Empty;
            System.Object.ctor.call(this);
            this.markup = html;
        },
        GetMarkup:function()
        {
            return this.markup;
        },
        SetMarkup:function(html)
        {
            this.markup = html;
        }
    }
};
JsTypes.push(UITK$UITKMarkup);
var UITK$Surface=
{
    fullname:"UITK.Surface",
    baseTypeName:"System.Object",
    staticDefinition:
    {
        cctor:function()
        {
            UITK.Surface.initialized = false;
            UITK.Surface.surface = null;
            UITK.Surface.children = new System.Collections.Generic.Dictionary$2.ctor(UITK.UITKComponentBase.ctor,UITK.UITKComponentBase.ctor);
            UITK.Surface.chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
        },
        Width$$:"System.Int32",
        get_Width:function()
        {
            return window.innerWidth;
        },
        Height$$:"System.Int32",
        get_Height:function()
        {
            return window.innerHeight;
        },
        Initialize:function()
        {
            var link=document.createElement("link");
            link.setAttribute("type","text/css");
            link.setAttribute("rel","stylesheet");
            link.setAttribute("href","http://yui.yahooapis.com/3.6.0/build/cssreset/cssreset-min.css");
            document.getElementsByTagName("head")[0].appendChild(link);
            UITK.Surface.surface = document.createElement("div");
            UITK.Surface.surface.id = "surface";
            $(UITK.Surface.surface).css("position","absolute");
            $(UITK.Surface.surface).css("left","0px");
            $(UITK.Surface.surface).css("right","0px");
            $(UITK.Surface.surface).css("top","0px");
            $(UITK.Surface.surface).css("bottom","0px");
            document.body.appendChild(UITK.Surface.surface);
            UITK.Surface.initialized = true;
        },
        Validate:function()
        {
            if(!UITK.Surface.initialized)
                UITK.Surface.Initialize();
            var $it1=UITK.Surface.children.get_Values().GetEnumerator();
            while($it1.MoveNext())
            {
                var child=$it1.get_Current();
                child.Validate();
            }
        },
        Redraw:function(component)
        {
            var id=component.get_Id();
            var element=document.getElementById(id);
            element.outerHTML = component.get_Markup().GetMarkup();
            var $it2=component.get_Styles().GetStyleDictionary().GetEnumerator();
            while($it2.MoveNext())
            {
                var style=$it2.get_Current();
                element.style[style.get_Key()] = style.get_Value();
            }
        },
        GenerateID:function()
        {
            var buffer=System.String.Empty;
            for(var i=0;i < 16;i++)
            {
                buffer += UITK.Surface.chars.charAt((Math.random() * UITK.Surface.chars.length));
            }
            return buffer;
        },
        AddComponent:function(component,x,y)
        {
            if(!UITK.Surface.initialized)
                UITK.Surface.Initialize();
            UITK.Surface.children.Add(component,component);
            component.get_Position().set_X(x);
            component.get_Position().set_Y(y);
            UITK.Surface.surface.innerHTML += "<div id=\'" + component.get_Id() + "\'></div>";
            component.Validate();
        }
    },
    assemblyName:"UITK",
    Kind:"Class",
    definition:
    {
        ctor:function()
        {
            System.Object.ctor.call(this);
        }
    }
};
JsTypes.push(UITK$Surface);
var UITK$UITKPosition=
{
    fullname:"UITK.UITKPosition",
    baseTypeName:"System.Object",
    assemblyName:"UITK",
    Kind:"Class",
    definition:
    {
        ctor:function(x,y)
        {
            System.Object.ctor.call(this);
            this.set_X(x);
            this.set_Y(y);
        },
        X$$:"System.Int32",
        get_X:function(){return this._X;},
        set_X:function(value){this._X = value;},
        Y$$:"System.Int32",
        get_Y:function(){return this._Y;},
        set_Y:function(value){this._Y = value;}
    }
};
JsTypes.push(UITK$UITKPosition);
var UITK$UITKStyles=
{
    fullname:"UITK.UITKStyles",
    baseTypeName:"System.Object",
    assemblyName:"UITK",
    Kind:"Class",
    definition:
    {
        ctor:function()
        {
            this.styles = new System.Collections.Generic.Dictionary$2.ctor(System.String.ctor,System.String.ctor);
            System.Object.ctor.call(this);
        },
        GetStyleDictionary:function()
        {
            return this.styles;
        },
        SetStyleDictionary:function(dictionary)
        {
            this.styles = dictionary;
        },
        GetRule:function(identifier)
        {
            if(this.styles.ContainsKey(identifier))
                return this.styles.get_Item$$TKey(identifier);
            return System.String.Empty;
        },
        SetRule$$String$$String:function(identifier,rule)
        {
            if(this.styles.ContainsKey(identifier))
                this.styles.set_Item$$TKey(identifier,rule);
            this.styles.Add(identifier,rule);
        },
        SetRule$$String$$Int32:function(identifier,rule)
        {
            if(this.styles.ContainsKey(identifier))
                this.styles.set_Item$$TKey(identifier,rule + "px");
            this.styles.Add(identifier,rule + "px");
        }
    }
};
JsTypes.push(UITK$UITKStyles);
